name: Node.js CI

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependency
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run build --if-present
    - name: deploy
      uses: vercel/action@v21
      with:
        githubToken: ${{ secrets.TOKEN_LOGIN }}
        

