name: Node.js CI

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependency
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run build --if-present
    - name: deploy
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.TOKEN_LOGIN }}
    - name: check deployment status
      run: curl --retry 10 --retry-delay 5 --retry-connrefused https://react-nivi30.vercel.app/
      timeout-minutes: 5
        

